# Hardware: esp-01s #3 on board #3
# MAC Addr: ec:fa:bc:61:c8:e0
substitutions:
  # This is the name used in the log files and for the device in Home Assistant
  name: bedroom-west-heatpump
  # This is the name originally used for the device in Home Assistant, and is
  # only used for the "rename" package.
  old_name: bedroom_west_heatpump
  # This is the friendly name used in Home Assistant for the device
  # and in the web interface.
  # It is also used in the climate component.
  friendly_name: West Bedroom HeatPump
  # This is the model of the heat pump, by the fanspeeds package
  model: MFZ-KA09NA
  # This is the remote temperature sensor used by the heat pump
  # It is a Home Assistant sensor entity, and is used to set the remote temperature
  # in the heat pump.
  remote_temp_sensor: sensor.westbedroom_htg_temperature

packages:
  wifi: !include common/wifi.yaml
  ipv6: !include common/ipv6.yaml
  sensors: !include common/sensors.yaml
  esp01: !include common/esp01.yaml
  heatpump-esp01: !include common/heatpump-esp01.yaml
  climate: !include common/heatpump-climate.yaml

web_server:
