# Recovery firmware for denheatpump
# This firmware includes fallback hotspot for recovery

substitutions:
  name: denheatpump
  friendly_name: Den Heatpump

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

logger:

# WiFi with production network first, then fallback hotspot
wifi:
  # Primary: Try to connect to production NoT network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

  # Connection timeout and retry settings
  reboot_timeout: 15min
  power_save_mode: none

  # CRITICAL: Fallback hotspot for recovery if production network fails
  ap:
    ssid: "${friendly_name} Recovery"
    password: !secret fallback_password

# Enable captive portal for recovery access
captive_portal:

# Enable OTA for recovery
ota:
  platform: esphome
  password: !secret ota_password

# Enable API for recovery
api:
  encryption:
    key: !secret api_key

# Enable web server for recovery
web_server:
  port: 80
  version: 3
