# Hardware: esp-01s #2
# MAC Addr: ec:fa:bc:c2:ac:58
substitutions:
  # This is the name used in the log files and for the device in Home Assistant
  name: denheatpump
  # This is the friendly name used in Home Assistant for the device
  # and in the web interface.
  # It is also used in the climate component.
  friendly_name: Den Heatpump
  # This is the model of the heat pump, by the fanspeeds package
  model: MSZ-GL06NA
  # This is the remote temperature sensor used by the heat pump
  # It is a Home Assistant sensor entity, and is used to set the remote temperature
  # in the heat pump.
  remote_temp_sensor: sensor.den_htg_temperature

packages:
  # Uncomment the next two lines to use a minimal WiFi configuration
  # esp01: !include common/esp01.yaml
  # wifi-minimal: !include common/wifi-minimal.yaml

  # Uncomment the next 5 lines to use a full WiFi configuration
  wifi: !include common/wifi.yaml
  ipv6: !include common/ipv6.yaml
  sensors: !include common/sensors.yaml
  heatpump-esp01: !include common/heatpump-esp01.yaml
  fanspeeds: !include common/heatpump-fanspeeds.yaml
  climate: !include common/heatpump-climate.yaml