---
# Dryer power status
# MAC: C4:5B:BE:E4:A2:70
substitutions:
  name: dryer
  friendly_name: "Clothes Dryer"
  # Plug state to set upon powerup (or after power loss)
  # See options here: https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_ON
  idle_wattage: "3.8"

packages:
  wifi: !include common/wifi.yaml
  # ipv6: !include common/ipv6.yaml
  sensors: !include common/sensors.yaml
  sonoff_s31: !include common/sonoff_s31.yaml
