esphome:
  name: esp32heatpump
  friendly_name: esp32heatpump
  platformio_options:
    build_flags: 
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rgXTHsxFpWpqZ8keD/h0cPLN6CN2ZznLLyXwh9JgTAk="

ota:
  - platform: esphome
    password: "5929ccc1f08289c79aca50ebe0a9b7eb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Heatpump Fallback Hotspot"
    password: "1SXRpeXi7AdU"

network:
  enable_ipv6: true
  min_ipv6_addr_count: 2


captive_portal:
    
external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump@2.5.0
