version: '3'

vars:
  MINIMAL_DEVICES:
    sh: "ls *-minimal.yaml | sed 's/-minimal.yaml//'"
  ALL_DEVICES:
    sh: "ls *.yaml | sed 's/\\.yaml//' | sed 's/-full//' | sed 's/-minimal//' | sort -u"

tasks:
  default:
    cmds:
      - task -l

  # ============================================================================
  # ESSENTIAL SECURITY VALIDATION
  # Basic security checks for single-user repository
  # ============================================================================

  security-validate:
    desc: "Run essential pre-deployment security validation"
    cmds:
      - cmd: |
          echo "🔍 Running essential security validation..."

          # Check if secrets.yaml exists
          if [[ ! -f "secrets.yaml" ]]; then
            echo "⚠️  secrets.yaml not found - generating from 1Password..."
            task secrets
          fi

          # Security validation is now handled by git-secrets, detect-secrets, and Python framework
          echo "ℹ️  ESPHome credential validation integrated into git-secrets and pre-commit hooks"

          echo "✅ Essential security validation completed"

  security-scan:
    desc: "Run basic security scan"
    cmds:
      - cmd: |
          echo "🔍 Running security scan..."

          # Run git-secrets if available
          if command -v git-secrets >/dev/null 2>&1; then
            git secrets --scan
          else
            echo "⚠️  git-secrets not installed - run: ./scripts/setup-security.sh"
          fi

          # Run pre-commit hooks if available
          if command -v pre-commit >/dev/null 2>&1; then
            pre-commit run --all-files
          else
            echo "⚠️  pre-commit not installed - run: ./scripts/setup-security.sh"
          fi

          echo "✅ Security scan completed"

  test-security:
    desc: "Run unit tests for Python security scripts"
    cmds:
      - cmd: |
          echo "🧪 Running security script tests..."
          python3 tests/run_tests.py
          echo "✅ Security tests completed"

  # ============================================================================
  # EXISTING TASKS WITH BASIC SECURITY INTEGRATION
  # ============================================================================

  clean:
    desc: "Removes the build directory for a specific device. Usage: task clean -- <device>"
    cmds:
      - rm -rf .esphome/build/{{.CLI_ARGS}}

  build:
    desc: "Builds the firmware for a specific device. Usage: task build -- <device>"
    deps:
      - task: clean
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
    cmds:
      - |
        if ls {{.CLI_ARGS}}-full.yaml >/dev/null 2>&1; then
          esphome compile {{.CLI_ARGS}}-full.yaml
        else
          esphome compile {{.CLI_ARGS}}.yaml
        fi

  upload:
    desc: "Uploads the firmware for a specific device. Usage: task upload -- <device>"
    deps:
      - task: security-validate
      - task: build
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
    cmds:
      - cmd: |
          upload_cmd="esphome upload {{.CLI_ARGS}}.yaml"
          if [ -f "{{.CLI_ARGS}}-full.yaml" ]; then
            upload_cmd="esphome upload {{.CLI_ARGS}}-full.yaml"
          fi

          # Run the command interactively, but capture exit code
          if $upload_cmd; then
            echo "✅ Upload completed successfully for {{.CLI_ARGS}}"
          else
            exit_code=$?
            echo "❌ Upload failed for {{.CLI_ARGS}} (exit code: $exit_code)"
            exit $exit_code
          fi

  build-minimal:
    desc: "Builds the minimal firmware for a specific device. Usage: task build-minimal -- <device>"
    cmds:
      - esphome compile {{.CLI_ARGS}}-minimal.yaml

  upload-minimal:
    desc: "Uploads the minimal firmware for a specific device. Usage: task upload-minimal -- <device>"
    deps:
      - task: security-validate
      - task: build-minimal
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
    cmds:
      - cmd: |
          # Run the command interactively, but capture exit code
          if esphome upload {{.CLI_ARGS}}-minimal.yaml; then
            echo "✅ Minimal upload completed successfully for {{.CLI_ARGS}}"
          else
            exit_code=$?
            echo "❌ Minimal upload failed for {{.CLI_ARGS}} (exit code: $exit_code)"
            exit $exit_code
          fi

  build-all:
    desc: "Builds the firmware for all devices."
    deps:
      - security-validate
    cmds:
      - for: { var: ALL_DEVICES }
        task: build
        vars: { CLI_ARGS: "{{.ITEM}}" }

  upload-all-two-stage:
    desc: "Uploads the firmware for all devices in two stages."
    deps:
      - security-validate
    cmds:
      - for: { var: ALL_DEVICES }
        task: upload-two-stage
        vars: { CLI_ARGS: "{{.ITEM}}" }

  upload-two-stage:
    desc: "Uploads the firmware for a single device in two stages."
    deps:
      - security-validate
    cmds:
      - task: upload-minimal-if-exists
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
      - task: upload
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }

  upload-minimal-if-exists:
    desc: "Uploads the minimal firmware for a specific device if it exists."
    cmds:
      - |
        if [ -f {{.CLI_ARGS}}-minimal.yaml ]; then
          task upload-minimal -- {{.CLI_ARGS}}
        fi

  build-all-minimal:
    desc: "Builds the minimal firmware for all devices."
    deps:
      - security-validate
    cmds:
      - for: { var: MINIMAL_DEVICES }
        task: build-minimal
        vars: { CLI_ARGS: "{{.ITEM}}" }

  upload-all-minimal:
    desc: "Uploads the minimal firmware for all devices."
    deps:
      - security-validate
    cmds:
      - for: { var: MINIMAL_DEVICES }
        task: upload-minimal
        vars: { CLI_ARGS: "{{.ITEM}}" }

  secrets:
    desc: "Generates secrets.yaml from 1Password"
    cmds:
      - ./scripts/generate_secrets.sh

  renovate:
    desc: "Run renovate to update dependencies"
    vars:
      GH_TOKEN:
        sh: op read --account CamiAndGeoff 'op://Private/GitHub Personal Access Token/token'
    cmds:
      - GITHUB_COM_TOKEN={{.GH_TOKEN}} RENOVATE_TOKEN={{.GH_TOKEN}} ./node_modules/.bin/renovate geoffdavis/esphome
