version: '3'

vars:
  MINIMAL_DEVICES:
    sh: "ls *-minimal.yaml | sed 's/-minimal.yaml//'"
  ALL_DEVICES:
    sh: "ls *.yaml | sed 's/\\.yaml//' | sed 's/-full//' | sed 's/-minimal//' | sort -u"

tasks:
  default:
    cmds:
      - task -l

  clean:
    desc: "Removes the build directory for a specific device. Usage: task clean -- <device>"
    cmds:
      - rm -rf .esphome/build/{{.CLI_ARGS}}

  build:
    desc: "Builds the firmware for a specific device. Usage: task build -- <device>"
    deps:
      - task: clean
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
    cmds:
      - |
        if ls {{.CLI_ARGS}}-full.yaml >/dev/null 2>&1; then
          esphome compile {{.CLI_ARGS}}-full.yaml
        else
          esphome compile {{.CLI_ARGS}}.yaml
        fi

  upload:
    desc: "Uploads the firmware for a specific device. Usage: task upload -- <device>"
    deps:
      - task: build
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
    cmds:
      - cmd: |
          upload_cmd="esphome upload {{.CLI_ARGS}}.yaml"
          if [ -f "{{.CLI_ARGS}}-full.yaml" ]; then
            upload_cmd="esphome upload {{.CLI_ARGS}}-full.yaml"
          fi

          if ! output=$($upload_cmd 2>&1); then
            if echo "$output" | grep -q "Error resolving IP address" || echo "$output" | grep -q "Network is unreachable"; then
              echo "Device {{.CLI_ARGS}} offline, skipping."
            else
              echo "$output"
              exit 1
            fi
          else
            echo "$output"
          fi

  build-minimal:
    desc: "Builds the minimal firmware for a specific device. Usage: task build-minimal -- <device>"
    cmds:
      - esphome compile {{.CLI_ARGS}}-minimal.yaml

  upload-minimal:
    desc: "Uploads the minimal firmware for a specific device. Usage: task upload-minimal -- <device>"
    deps:
      - task: build-minimal
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
    cmds:
      - cmd: |
          if ! output=$(esphome upload {{.CLI_ARGS}}-minimal.yaml 2>&1); then
            if echo "$output" | grep -q "Error resolving IP address" || echo "$output" | grep -q "Network is unreachable"; then
              echo "Device {{.CLI_ARGS}} offline, skipping."
            else
              echo "$output"
              exit 1
            fi
          else
            echo "$output"
          fi

  build-all:
    desc: "Builds the firmware for all devices."
    cmds:
      - for: { var: ALL_DEVICES }
        task: build
        vars: { CLI_ARGS: "{{.ITEM}}" }

  upload-all-two-stage:
    desc: "Uploads the firmware for all devices in two stages."
    cmds:
      - for: { var: ALL_DEVICES }
        task: upload-two-stage
        vars: { CLI_ARGS: "{{.ITEM}}" }

  upload-two-stage:
    desc: "Uploads the firmware for a single device in two stages."
    cmds:
      - task: upload-minimal-if-exists
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
      - task: upload
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }

  upload-minimal-if-exists:
    desc: "Uploads the minimal firmware for a specific device if it exists."
    cmds:
      - |
        if [ -f {{.CLI_ARGS}}-minimal.yaml ]; then
          task upload-minimal -- {{.CLI_ARGS}}
        fi

  build-all-minimal:
    desc: "Builds the minimal firmware for all devices."
    cmds:
      - for: { var: MINIMAL_DEVICES }
        task: build-minimal
        vars: { CLI_ARGS: "{{.ITEM}}" }

  upload-all-minimal:
    desc: "Uploads the minimal firmware for all devices."
    cmds:
      - for: { var: MINIMAL_DEVICES }
        task: upload-minimal
        vars: { CLI_ARGS: "{{.ITEM}}" }

  secrets:
    desc: "Generates secrets.yaml from 1Password"
    cmds:
      - ./scripts/generate_secrets.sh

  renovate:
    desc: "Run renovate to update dependencies"
    vars:
      GH_TOKEN:
        sh: op read --account CamiAndGeoff 'op://Private/GitHub Personal Access Token/token'
    cmds:
      - GITHUB_COM_TOKEN={{.GH_TOKEN}} RENOVATE_TOKEN={{.GH_TOKEN}} ./node_modules/.bin/renovate geoffdavis/esphome