---
substitutions:
  name: tg-lrtv
  old_name: tg_lrtv
  friendly_name: "Living Room Entertainment"
  # Plug state to set upon powerup (or after power loss)
  # See options here: https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_ON
  # TGWF115APM (Big 15A plug)
  current_resistor: "0.00228"
  voltage_divider: "2120"
  wattage_multiplier: "0.001"
  voltage: "120.0"

packages:
  wifi: !include common/wifi-minimal.yaml
  esp01: !include common/esp01.yaml

web_server:
