substitutions:
  name: voronica-outlet
  old_name: pruscilla-outlet-tg
  friendly_name: "Voronica Outlet"
  # Plug state to set upon powerup (or after power loss)
  # See options here: https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_ON
  # TGWF115PQM (10A) outlet
  current_resistor: "0.0019"
  voltage_divider: "2150"
  wattage_multiplier: "0.001"
  voltage: "120.0"

packages:
  wifi: !include common/wifi.yaml
  ipv6: !include common/ipv6.yaml
  sensors: !include common/sensors.yaml
  esp01: !include common/esp01.yaml
  topgreener: !include common/outlet-topgreener.yaml

web_server:
