# MAC:
# sn
substitutions:
  name: xmas-tree-outlet
  old_name: xmas_tree_outlet
  friendly_name: "Christmas Tree Outlet"

packages:
  wifi: !include common/wifi.yaml
  ipv6: !include common/ipv6.yaml
  rename: !include common/rename.yaml
  sensors: !include common/sensors.yaml
  feit: !include common/feit_outlet.yaml
