# File: common/sensor/bme280.yaml
# This file contains the configuration for a BME280 sensor connected to an I2C bus.
# It is included in various ESPHome configurations to standardize BME280 sensor setup.
# It sets up an i2c bus and configures the BME280 sensor to read temperature, humidity, and pressure.

i2c:
  - id: ${bme280_i2c_id}
    sda: ${bme280_i2c_sda}
    scl: ${bme280_i2c_scl}
    scan: True

sensor:
  # BME280 on I2C bus
  - platform: bme280_i2c
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: "${friendly_name} BME280 Temperature"
    pressure:
      name: "${friendly_name} BME280 Pressure"
    humidity:
      name: "${friendly_name} BME280 Humidity"
