# File: common/sensor/temt6000.yaml
# This file contains the configuration for a TEMT6000 light sensor connected to a GPIO pin.
# It is included in various ESPHome configurations to standardize TEMT6000 sensor setup.

sensor:
  - platform: adc
    pin: ${temt6000_pin}
    name: ${friendly_name} Illuminance
    unit_of_measurement: lx
    filters:
        - lambda: |-
            return (x/10000.0) * 2000000.0;
