# File: include/esp01.yaml
# Configuration defaults for an ESP01 board
# This file is included in all ESPHome YAML files that use an ESP01 board.

esphome:
  name: $name
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

logger:
