---
# Feit electric wifi-switchable double outlet
# Sold at costco, runs Tuya natively.

esphome:
  name: ${name}

esp8266:
  board: esp01_1m
  # We want to use the ESP8266 built-in persistent storage.
  # This allows us to restore the plug state after a power loss.
  # https://esphome.io/components/esp8266
  restore_from_flash: true

# Feit electric outlets have a single button on GPIO13
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${friendly_name} Status

switch:
  - platform: gpio
    name: ${friendly_name} Relay
    pin: GPIO12
    id: relay
    icon: mdi:printer-3d
    on_turn_on:
      - light.turn_on: red_led_light
    on_turn_off:
      - light.turn_off: red_led_light

output:
  - platform: esp8266_pwm
    id: feit_red_led
    pin:
      number: GPIO5
      inverted: true

status_led:
  # Blue Light
  pin:
    number: GPIO4
    inverted: true

light:
  - platform: monochromatic
    name: ${friendly_name} Red LED
    output: feit_red_led
    id: red_led_light
