# File: common/nodemcuv2.yaml
# This file contains the basic configuration for a NodeMCU v2 ESPHome device.
# It includes the board type and basic ESPHome settings.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: nodemcuv2

# Enable logging
logger:
