---
# File: common/particle-d1mini32.yaml
# Base configuration for a Wemons D1 Mini 32 board with Particle sensor support.
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: wemos_d1_mini32

uart:
  tx_pin: ${pms_uart_tx}
  rx_pin: ${pms_uart_rx}
  id: pms_uart
  baud_rate: 9600

logger:
  level: INFO # Set to INFO to see basic operation, WARN to see warnings,
              # or DEBUG for detailed debugging
  logs:
    pmsx003: INFO  # Set to INFO to see basic operation, WARN to see
                   # warnings, or DEBUG for detailed debugging
