# Defaults for wifi, api, and OTA connectivity
# This file is included in all ESPHome YAML files.

# Configure the WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} ESP"
    password: !secret fallback_password

# Enable captive portal for fallback access
# This allows access to the device even if the WiFi connection fails
# It provides a simple web interface to configure the device
captive_portal:

# Enable Home Assistant API for integration
# This allows the device to communicate with Home Assistant
# The API key is used for secure communication
# The key is stored in secrets.yaml for security
api:
  encryption:
    key: !secret api_key

# Enable Over-The-Air (OTA) updates
# This allows the device to be updated wirelessly
# The OTA password is used for secure updates
# The password is stored in secrets.yaml for security
ota:
  platform: esphome
  password: !secret ota_password

# Enable Web server, version 3
# This provides a web interface to interact with the device
# The web server runs on port 80
web_server:
  port: 80
  version: 3

# Wifi related sensors
# These sensors provide information about the WiFi connection
sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 30s

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID